[package]
name = "how-bad-was-my-roll"
version = "0.1.0"
authors = ["Emerson Harkin <emerson.f.harkin@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-bigint = "0.3.0"
